PREFIX mydb: <http://mydb.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

SELECT distinct ?property
where {
   ?s ?property ?o .
}
ORDER BY ASC(?property)