PREFIX mydb: <http://mydb.org/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX schema: <http://schema.org/>

SELECT ?given ?family
WHERE
{ ?s schema:givenName ?given .
  OPTIONAL { ?s schema:familyName ?family } .
}